name: Log Checker

on:
  push:
  pull_request:

jobs:
  run-log-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Make script executable
        run: chmod +x log_checker.sh

      - name: Run log checker
        run: ./log_checker.sh sample.log
